name: aircraft_mapper
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - netCDF4=1.6.2
  - numpy=1.26.4
  - bokeh=3.6.0
  - scipy=1.13.1
  - pandas=2.2.2
  - pytest=7.4.4
  - Pathlib=1.0.1
  - pyngl=1.6.1
  - holoviews=1.19.1
  - pip=23.2
  - pip:
    - nbconvert[webpdf]
    - metpy==1.5.1
