name: aircraft_mapper
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.1.1
  - netCDF4=1.7.2
  - numpy=2.1.3
  - bokeh=3.6.0
  - scipy=1.14.1
  - pandas=2.2.3
  - pytest=8.3.3
  - Pathlib=1.0.1
  - holoviews=1.19.1
  - selenium=4.24.0
  - firefox=132.0
  - geckodriver=0.35.0
  - cartopy=0.24.0
  - xarray=2024.10.0
  - matplotlib=3.9.2
  - pip=23.2
  - pip:
    - nbconvert[webpdf]
    - metpy==1.5.1
